name: Publish to JitPack on Release

on:
  release:
    types: [published] # 只在发布正式Release时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # 可选：排除预发布版本
    if: ${{ !github.event.release.prerelease }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # JitPack需要完整的git历史记录

      - name: Verify Release Tag
        id: verify-tag
        run: |
          # 检查tag名称是否符合语义化版本规范
          if [[ ! ${{ github.event.release.tag_name }} =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+)?$ ]]; then
            echo "::error::Tag name ${{ github.event.release.tag_name }} does not follow semantic versioning"
            exit 1
          fi
          echo "Valid tag: ${{ github.event.release.tag_name }}"

      - name: Trigger JitPack build
        env:
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
        run: |
          # 提取版本号（去掉可能的v前缀）
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v} # 去掉v前缀
          
          echo "Triggering JitPack build for version $VERSION"
          
          # 使用JitPack API触发构建
          curl -X POST "https://jitpack.io/api/build" \
            -H "Content-Type: application/json" \
            -d "{
              \"groupId\": \"com.github.${{ github.repository_owner }}\",
              \"artifactId\": \"${{ github.event.repository.name }}\",
              \"version\": \"$VERSION\"
            }" \
            -u "${{ github.repository_owner }}:$JITPACK_TOKEN"

      - name: Verify JitPack Build
        run: |
          echo "Check build status at:"
          echo "https://jitpack.io/#${{ github.repository }}/$VERSION"
