name: Publish to JitPack on Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Release Tag
        run: |
          if [[ ! "${{ github.event.release.tag_name }}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version tag: ${{ github.event.release.tag_name }}"
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Trigger JitPack build
        env:
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Triggering build for version: $VERSION"
          
          # 调试：显示仓库信息
          echo "Repository: ${{ github.repository }}"
          echo "Owner: ${{ github.repository_owner }}"
          
          RESPONSE=$(curl -v -X POST "https://jitpack.io/api/build" \
            -H "Content-Type: application/json" \
            -d "{
              \"groupId\": \"com.github.${{ github.repository_owner }}\",
              \"artifactId\": \"${{ github.event.repository.name }}\",
              \"version\": \"$VERSION\"
            }" \
            -u "${{ github.repository_owner }}:$JITPACK_TOKEN")
          
          echo "API Response: $RESPONSE"
          if [[ -z "$RESPONSE" || $RESPONSE != *"status"* ]]; then
            echo "::error::JitPack API request failed"
            exit 1
          fi

      - name: Verify Build Status
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Check build progress at:"
          echo "https://jitpack.io/#${{ github.repository }}/$VERSION"
          echo "If not started, manually click 'Build' on JitPack page"
